trigger:
- master
- release/*

resources:
  repositories:
  - repository: buildtools
    type: git
    name: aspnet-BuildTools
    ref: refs/heads/master

jobs:
- template: .azure/templates/project-ci.yml@buildtools
  parameters:
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 8.x
      inputs:
        versionSpec: 8.x
